const ADD_TWEET = "ADD_TWEET";
const REMOVE_TWEET = "REMOVE_TWEET";
const UPDATE_TWEET = "UPDATE_TWEET";
const UPDATE_STATUS = "UPDATE_STATUS";
const ARCHIEVE_STATUS = "ARCHIEVE_STATUS";
const OPTION_STATUS = "OPTION_STATUS";

export { ADD_TWEET, REMOVE_TWEET, UPDATE_TWEET, UPDATE_STATUS, ARCHIEVE_STATUS, OPTION_STATUS }